version: '3.8'

x-airflow-common:
  &airflow-common
  image: apache/airflow:2.7.1-python3.9
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://user_etf:password_etf@postgres/etf_data
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW_UID: 50000
    _PIP_ADDITIONAL_REQUIREMENTS: yfinance pandas sqlalchemy psycopg2-binary
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
  depends_on:
    &airflow-common-depends-on
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:15
    container_name: etf_db
    environment:
      POSTGRES_USER: user_etf
      POSTGRES_PASSWORD: password_etf
      POSTGRES_DB: etf_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # CORRECTION 1 : Init SQL automatique
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - etf_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_etf -d etf_data"]
      interval: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_interface
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
       # CORRECTION 2 : Persistance PgAdmin
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - etf_network

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - etf_network

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: scheduler
    networks:
      - etf_network

  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    # CORRECTION 3 : Automatisation de la connexion Airflow
    command: >
      bash -c "
      /entrypoint.sh bash -c '
      airflow db migrate &&
      airflow users create -u airflow -p airflow -e admin@admin.com -f Marving -l Gustave -r Admin;
      airflow connections add postgres_etf --conn-uri postgresql://user_etf:password_etf@postgres:5432/etf_data
      '
      "
    networks:
      - etf_network

  dashboard:
    build: ./dashboard
    container_name: dashboard_ui
    ports:
      - "8501:8501"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_NAME: etf_data
      DB_USER: user_etf
      DB_PASS: password_etf
    networks:
      - etf_network

volumes:
  postgres_data:
  pgadmin_data: # Volume pour PgAdmin

networks:
  etf_network:
    driver: bridge